name: Scheduled Merge (JST)

on:
  schedule:
    - cron: "10 7 26 12 *" # JST 16:10 に対応する UTC 7:10

jobs:
  merge-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Get Pull Request Number
        id: get_pr
        run: |
          # dev から main へのオープンなプルリクエストのうち、最新のものを取得
          PR_NUMBER=$(gh pr list --base main --head dev --state open --json number -q '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER"
          echo "::set-output name=pr_number::$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        if: steps.get_pr.outputs.pr_number != ''
        run: |
          gh pr merge ${{ steps.get_pr.outputs.pr_number }} --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
